### ISSUE TITLE
HOW TO DOWNLOAD UR VERSION OF ARCH LINUX

### ISSUE THREAD

**Issue by MostafaMohamed2002** [kabinspace/dotfiles#1]

**Comment by kabinspace** [comment]
I downloaded the latest version of arch linux which is available on their official [site](https://archlinux.org/download/) itself.

**Comment by kabinspace** [comment]
If you are talking about downloading and applying my config in your arch linux then you should install [stow](https://www.gnu.org/software/stow/) and follow these [commands](https://github.com/kabinspace/dotfiles#-setup).
